services:
  postgres:
    image: postgres:latest
    container_name: xd-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: deep
      POSTGRES_PASSWORD: smthn
      POSTGRES_DB: xd_db

    ports:
      - '5432:5432'

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U deep -d xd_db']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: xd-redis
    restart: unless-stopped

    ports:
      - '6379:6379'

    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
