import { QueryProvider } from '@/components/providers/query-provider';
import { Geist_Mono, Inter, Geist } from 'next/font/google';
import { Toaster } from '@/components/ui/sonner';
import localFont from 'next/font/local';
import type { Metadata } from 'next';
import { cn } from '@/lib/utils';
import './globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geist = Geist({
  variable: '--font-geist',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'scalable chat app',
  description: 'Generated by create next app',
};

const cooper = localFont({
  src: [
    {
      path: '../public/fonts/CooperLightBT.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/CooperLightItalicBT.ttf',
      weight: '300',
      style: 'italic',
    },
    {
      path: '../public/fonts/CooperBoldBT.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/fonts/CooperBoldItalicBT.ttf',
      weight: '700',
      style: 'italic',
    },
  ],
  variable: '--font-cooper',
  display: 'swap',
});

const cooperLt = localFont({
  src: [
    {
      path: '../public/fonts/CooperLtBTLight.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/CooperLtBTLightItalic.ttf',
      weight: '300',
      style: 'italic',
    },
    {
      path: '../public/fonts/CooperLtBTBold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/fonts/CooperLtBTBoldItalic.ttf',
      weight: '700',
      style: 'italic',
    },
  ],
  variable: '--font-cooper-lt',
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        geist.variable,
        geistMono.variable,
        inter.variable,
        cooper.variable,
        cooperLt.variable,
        'font-inter'
      )}
    >
      <body className={`${geistMono.variable} antialiased`}>
        <QueryProvider>{children}</QueryProvider>
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
